# Generated by Django 2.2 on 2021-02-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Cat',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Cat'),
        ),
    ]
