# Generated by Django 2.2 on 2021-02-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210201_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Group',
        ),
    ]
