# Generated by Django 2.2 on 2021-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210203_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите текст для новго поста', verbose_name='Текст поста'),
        ),
    ]
